name: QIT

on:
    workflow_run:
        workflows: [ 'Build and distribute' ]
        types: [ completed ]
        branches: [ 'dev/main', 'dev/release/**' ]
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch || github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build plugin package
        if: >-
            github.event_name == 'workflow_dispatch' ||
            (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
        uses: inpsyde/reusable-workflows/.github/workflows/build-and-distribute.yml@main
        secrets:
            GITHUB_USER_EMAIL: ${{ secrets.DEPLOYBOT_EMAIL }}
            GITHUB_USER_NAME: ${{ secrets.DEPLOYBOT_USER }}
            GITHUB_USER_SSH_KEY: ${{ secrets.DEPLOYBOT_SSH_PRIVATE_KEY }}
            GITHUB_USER_SSH_PUBLIC_KEY: ${{ secrets.DEPLOYBOT_SSH_PUBLIC_KEY }}
            COMPOSER_AUTH_JSON: ${{ secrets.PACKAGIST_AUTH_JSON }}
        with:
            NODE_VERSION: 20
            PACKAGE_NAME: 'zettle-pos-integration'

    qit:
        strategy:
            fail-fast: false
            matrix:
                test: ['phpcompatibility', 'validation', 'activation', 'woo-api', 'security', 'malware']
        uses: inpsyde/reusable-workflows/.github/workflows/woo-qit.yml@main
        needs: build
        secrets:
            WOO_PARTNER_USER: ${{ secrets.WOO_PARTNER_USER }}
            WOO_PARTNER_SECRET: ${{ secrets.WOO_PARTNER_SECRET }}
        with:
            ARTIFACT_NAME: ${{ needs.build.outputs.artifact }}
            QIT_TEST: ${{ matrix.test }}
            PLUGIN_FOLDER_NAME: 'zettle-pos-integration'
