name: Testing with WP

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2']
    env:
      IZETTLE_API_KEY: ${{ secrets.IZETTLE_API_KEY }}
      IZETTLE_PLACEHOLDER_IMAGES_ENABLED: 1

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - uses: actions/checkout@v1

      - name: Packagist.com Auth
        run: composer config --global --auth http-basic.repo.packagist.com token ${{ secrets.PACKAGIST_TOKEN }}

      - name: Install dependencies
        uses: ramsey/composer-install@v4
        with:
          composer-options: "--prefer-dist"

      - name: Install test dependencies
        uses: ramsey/composer-install@v4
        with:
            working-directory: tests/wp-integration/

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
        working-directory: tests/wp-integration/
