name: Testing

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2', '8.3', '8.4']
    env:
      IZETTLE_API_KEY: ${{ secrets.IZETTLE_API_KEY }}
      IZETTLE_PLACEHOLDER_IMAGES_ENABLED: 1

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - uses: actions/checkout@v1

      - name: Packagist.com Auth
        run: composer config --global --auth http-basic.repo.packagist.com token ${{ secrets.PACKAGIST_TOKEN }}

      - name: Validate composer.json
        run: composer validate

      - name: Run PHPUnit
        run: ./phpunit.sh
  coding-standards-analysis-php:
      uses: inpsyde/reusable-workflows/.github/workflows/coding-standards-php.yml@main
      secrets:
          COMPOSER_AUTH_JSON: ${{secrets.PACKAGIST_AUTH_JSON}}
      with:
          PHP_VERSION: '8.2'
          PHPCS_ARGS: '--report-full --runtime-set ignore_warnings_on_exit 1'
  static-code-analysis-php:
      uses: inpsyde/reusable-workflows/.github/workflows/static-analysis-php.yml@main
      secrets:
          COMPOSER_AUTH_JSON: ${{secrets.PACKAGIST_AUTH_JSON}}
      with:
          PHP_VERSION: '8.2'
          PHPSTAN_ARGS: '--no-progress --memory-limit=2G'
